# TODO replace name with name of ebook: 101: Intro to Web, 411: Front-Ends with React...etc
site_name: JS211 - Foundations in Programming

# TODO run `git clone https://github.com/squidfunk/mkdocs-material.git`
# TODO run `pip install -r mkdocs-material/requirements.txt`
# TODO run `mkdocs build` to build the static files into "/site"
# TODO run `mkdocs serve` to serve those files 
# TODO view at http://127.0.0.1:8000
# TODO replace all CAPITALIZED words with appropriate titles

# defines where the markdown to build from
# docs_dir: 'test-node-book'

# defines where to put the generated static files
# site_dir: 'docs'

# "pages" has been deprecated
# use this to create the nav bar on the left-side of the window view

nav:
    - Home: 'index.md'
    # - 'Module One: TITLE': 
      # - 'Class * Pre-Lessons': 
      #   - LESSON TITLE: module-2/lesson-*.md
      #   - Class 9 TITLE: module-2/class-*.md
    # - 'Module Two: TITLE':
    # - 'Module Three: TITLE':
    # - 'Module Four: TITLE':
    - 'Templates':
      - 'Class * Pre-Lessons': 
        - Intro to Material-Mkdocs: module-1/pre-class-lessons/lessonOutlineTemplate.md
        - Class 1, Template: module-1/class-plans/classOutlineTemplate.md

# defines the styles, usually just a single name but `custom_dir` overrides this behavior
theme:
  name: null
  custom_dir: mkdocs-material/material
  palette:
    scheme: slate
    primary: black
    accent: deep orange
    # Defines the logo in the top-left, file must be in the /doc directory
  logo: CE_WhiteBlue_Icon.png
  
  # ? Not rendering as expected??
  extra:
    copyright: Copyright &copy; 2013 - 2021 Austin Coding Academy
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/AustinCodingAcademy
      - icon: fontawesome/brands/medium
        link: https://medium.com/@austincoding
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/school/austincodingacademy/
      - icon: fontawesome/brands/instagram
        link: https://www.instagram.com/austincodingacademy
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/austincoding
      - icon: fontawesome/brands/facebook
        link: https://www.facebook.com/AustinCodingAcademy/


  
  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      clickable_checkbox: true
  - def_list
  - pymdownx.tabbed


 

# Can add icons throughout the ebook https://materialdesignicons.com/
#  - pymdownx.inlinehilite
  # - pymdownx.keys