# TODO replace name with name of ebook: 101: Intro to Web, 411: Front-Ends with React...etc
site_name: JS211 - Foundations in Programming

# TODO inside `ebook/`
# TODO run `git clone https://github.com/squidfunk/mkdocs-material.git`
# TODO run `pip install -r mkdocs-material/requirements.txt`
# TODO run `mkdocs build` to build the static files into "/site"
# TODO run `mkdocs serve` to serve those files 
# TODO view at http://127.0.0.1:8000
# TODO replace all CAPITALIZED words with appropriate titles

# defines where the markdown to build from
# docs_dir: 'docs'

# defines where to put the generated static files
# site_dir: 'site'

# "pages" has been deprecated
# use this to create the nav bar on the left-side of the window view

nav:
    - Home: 'index.md'
    - 'Pre-Course Prep':
      - 'Part 1: How To Succeed':
        - The Flipped Classroom: preCourse/succeedInThisCourse.md
      - 'Part 2: Set Up':
        - Prepare Your Machine: preCourse/setupInstructions.md
      - 'Part 3: Coding and Programming':
        - Coding + Programming: preCourse/codingAndProgramming.md
      - 'Part 4: Intro to JavaScript':
        - What is JavaScript: preCourse/whatIsJavaScript.md
        - Variables & Functions: preCourse/variablesAndFunctions.md
        - Data Types: preCourse/dataTypes.md
        - Type Number: preCourse/typeNumber.md
        - Type Boolean: preCourse/typeBoolean.md
        - Comparison Operator:  preCourse/comparisonOperators.md
        - typeof Operator:  preCourse/typeofOperator.md
        - Function Signatures:  preCourse/functionSignatures.md
        - Practice Data Types & Functions: preCourse/dataTypesAndFunctions.md
        - Date & Time Repo: preCourse/firstRepo.md
      - 'Part 5: Nitty Gritty': 
        - History of JavaScript: preCourse/historyOfJavaScript.md
        - ES5 vs ES6: preCourse/es5&es6.md
        - Intro to TDD: preCourse/testDriveDevelopmentIntro.md
        - Submitting Homework: preCourse/submittingHomework.md
      - Day 1 Checklist: preCourse/preClassChecklist.md
    - 'Module 1: The Fundamentals': 
      - Class 1 JS Review: module-1/class-1.md
      - 'Class 2 Pre-Lessons': 
        - Conditionals: module-1/conditionals.md
        - Develop - Speaking: module-1/developSeries-SpeakingIsEasy.md
        - Class 2 RPS: module-1/class-2.md
      - 'Class 3 Pre-Lessons': 
        - Type String: module-1/typeString.md
        - Type Array: module-1/typeArray.md
        - Develop-Not Weak: module-1/developSeries-NotWeak.md
        - Class 3 Pig Latin: module-1/class-3.md
      - 'Class 4 Pre-Lessons': 
        - Type Object-Literal: module-1/typeObjectLiteral.md  
        - Loops in JS: module-1/js-loops.md  
        - Develop - Your Prison: module-1/developSeries-PrisonOfYourMind.md
        - Class 4 TicTacToe: module-1/class-4.md
    - 'Module 2: Functional Programming':
        - 'Class 5 Pre-Lessons':
          - The DOM: module-2/theDom.md
          - Develop - Stop Thinking: module-2/developSeries-StopThinking.md
          - Big O Pt. 1: module-2/bigO-pt1.md
          - Class 5 The DOM: module-2/class-5.md
        - 'Class 6 Pre-Lessons': 
          - Bind & This: module-2/bindThis.md
          - Develop - Exhausted Brain: module-2/developSeries-FixTheExhaustedBrain.md
          - Big O Pt. 2: module-2/bigO-pt2.md
          - Class 6 Towers Of Hanoi: module-2/class-6.md
        - 'Class 7 Pre-Lessons':
          - HOF pt. 1: module-2/higherOrderFunctions-pt1.md
          - Develop - Millennial Weakness: module-2/developSeries-MillennialWeakness.md  
          - Big O Pt. 3: module-2/bigO-pt3.md
          - Class 7 MasterMind: module-2/class-7.md
        - 'Class 8 Pre-Lessons':
          - HOF pt. 2: module-2/higherOrderFunctions-pt2.md
          - Big O Pt. 4: module-2/bigO-pt4.md
          - Class 8 find & findIndex: module-2/class-8.md  
    - 'Module 3: OOP & Algorithms':
        - 'Class 9 Pre-Lessons':
          - OOP-pt.1: module-3/oop-pt1.md
          - Closures: module-3/closures.md
          - Class 9 Mission to Mars: module-3/class-9.md
        - 'Class 10 Pre-Lessons':  
          - OOP-pt.2: module-3/oop-pt2.md
          - Class Keyword: module-3/oop-nuts+bolts.md
          - Extending Classes: module-3/extendClasses.md
          - Class 10 Bank Account: module-3/class-10.md
        - 'Class 11 Pre-Lessons':
          - Algorithms pt.1: module-3/algorithms-pt1.md
          - Class 11 Sorting & Fundamentals: module-3/class-11.md
        - 'Class 12 Pre-Lessons':
          - Develop - Thinking Programmer: module-3/developeSeries-thinkingLikeAProgrammer.md
          - Algorithms pt.2: module-3/algorithms-pt2.md
          - Class 12 Hackathon: module-3/class-12.md
    - 'Module 4: Developing in Node':
        - 'Class 13 Pre-Lessons':
          - Data From APIs: module-4/dataFromAPIs.md
          - Promises: module-4/promises.md
          - Fetch API: module-4/fetch-API.md
          - Class 13 Address Book: module-4/class-13.md
        - 'Class 14 Pre-Lessons':
          - API Keys: module-4/api-keys.md
          - Fetch Error Handling: module-4/fetch-errorHandling.md
          - Develop - Code Music: module-4/developSeries-MusicForYourBrain.md
          - Class 14 New API App: module-4/class-14.md
        - 'Class 15 Pre-Lessons':
          - Function Currying: module-4/functionCurrying.md
          - Function Recursion: module-4/functionRecursion.md
          - Dependency Injection: module-4/testingFetch.md
          - Class 15 Testing Fetch: module-4/class-15.md
        - 'Class 16 Pre-Lessons':
          - Pure Functional Programming: module-4/pureFunctions.md
          - Immutability: module-4/immutability.md
          - Class 16 Lodash & Recursion: module-4/class-16.md
    - Report A Bug: additionalResources/reportABug.md
    - 'Additional Resources':
      - Interview Training: additionalResources/interviewChallenges.md
      - Student Presentations: additionalResources/studentPresentations.md
      - Develop Series Collection: additionalResources/developSeries.md
      - 'Questions for Discussion Collections':
        - Day 1 QFD: additionalResources/questionsForDiscussion/qfd-class-1.md
        - Day 2 QFD: additionalResources/questionsForDiscussion/qfd-class-2.md
        - Day 3 QFD: additionalResources/questionsForDiscussion/qfd-class-3.md
        - Day 4 QFD: additionalResources/questionsForDiscussion/qfd-class-4.md
        - Day 5 QFD: additionalResources/questionsForDiscussion/qfd-class-5.md
        - Day 6 QFD: additionalResources/questionsForDiscussion/qfd-class-6.md
        - Day 7 QFD: additionalResources/questionsForDiscussion/qfd-class-7.md
        - Day 8 QFD: additionalResources/questionsForDiscussion/qfd-class-8.md
        - Day 9 QFD: additionalResources/questionsForDiscussion/qfd-class-9.md
        - Day 10 QFD: additionalResources/questionsForDiscussion/qfd-class-10.md
        - Day 11 QFD: additionalResources/questionsForDiscussion/qfd-class-11.md
        - Day 12 QFD: additionalResources/questionsForDiscussion/qfd-class-12.md
        - Day 13 QFD: additionalResources/questionsForDiscussion/qfd-class-13.md
        - Day 14 QFD: additionalResources/questionsForDiscussion/qfd-class-14.md
        - Day 15 QFD: additionalResources/questionsForDiscussion/qfd-class-15.md
        - Day 16 QFD: additionalResources/questionsForDiscussion/qfd-class-16.md
      - Blog Prompts: additionalResources/blogPrompts.md
      - Keyboard Shortcuts: additionalResources/keyboardShortcuts.md
      - Git & CLI Commands: additionalResources/gitCommands.md
      - Learn Your CLI: additionalResources/learnYourCLI.md
      - Graduation Prerequisites: additionalResources/graduationPrerequisites.md
      - Presentation Qualifications: additionalResources/presentationsQualifications.md
      - 'Bonus Materials':
        - Checkers App: additionalResources/bonusMaterial/checkersBonus.md
        - JavaScripting.js: additionalResources/bonusMaterial/javascriptingBonus.md

# defines the styles, usually just a single name but `custom_dir` overrides this behavior
theme:
  name: material
  # was null
  custom_dir: mkdocs-material/material
  # not rendering as expected...
  repo_url: https://github.com/AustinCodingAcademy/JS211-8week-ebook
  repo_name: AustinCodingAcademy/JS211-8week-ebook
  edit_uri: edit/master/docs/
  palette:
    scheme: slate
    primary: black
    accent: cyan
    # Defines the logo in the top-left, file must be in the /doc directory
  logo: CE_WhiteBlue_Icon.png
  features:
    - navigation.instant
    - navigation.top
    # - navigation.tabs


  # ? Not rendering as expected?? Supposed to be in the footer
  extra:
    copyright: Copyright &copy; 2013 - 2021 Austin Coding Academy
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/AustinCodingAcademy
      - icon: fontawesome/brands/medium
        link: https://medium.com/@austincoding
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/school/austincodingacademy/
      - icon: fontawesome/brands/instagram
        link: https://www.instagram.com/austincodingacademy
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/austincoding
      - icon: fontawesome/brands/facebook
        link: https://www.facebook.com/AustinCodingAcademy/

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# extensions to create nicer code fences and highlighting
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      clickable_checkbox: true
  - def_list
  - pymdownx.tabbed


 

# Can add icons throughout the ebook https://materialdesignicons.com/
#  - pymdownx.inlinehilite
  # - pymdownx.keys

  # or
  # https://github.com/facelessuser/mkdocs-material-extensions/